version: 5
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: "Asia/Yangon"
  labels:
    - "dependencies"
  open-pull-requests-limit: 5000000
